-- =============================================================================
-- Dino Arm Tourney — Production schema baseline (2026-04-30)
-- =============================================================================
-- Source of truth for a fresh Postgres / Supabase database.
-- Generated by introspecting the dev project (hmvnelyzqqdfidjalsha) on
-- 2026-04-30 to realign prod (nmglfsqwlhacdcqqmday) which had drifted.
--
-- Apply order on a clean public schema:
--   1. supabase/schema.sql   (this file)
--   2. supabase/seed.sql     (rule_profiles reference data)
--
-- Wipe-and-restore recipe (Supabase Studio → SQL Editor on prod):
--   drop schema public cascade;
--   create schema public;
--   grant all  on schema public to postgres, service_role;
--   grant usage on schema public to anon, authenticated;
--   -- then paste THIS file, then seed.sql.
--
-- Auth users (auth.*) and storage objects (storage.*) are NOT touched.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Extensions
-- -----------------------------------------------------------------------------
create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";

-- -----------------------------------------------------------------------------
-- Sequences (explicit, non-serial)
-- -----------------------------------------------------------------------------
create sequence if not exists public.audit_log_id_seq as bigint start 1;

-- =============================================================================
-- TABLES (columns + defaults + NOT NULL only; constraints added below)
-- =============================================================================

-- profiles --------------------------------------------------------------------
create table if not exists public.profiles (
    id                uuid not null,
    full_name         text,
    phone             text,
    role              text not null default 'athlete',
    created_at        timestamptz not null default now(),
    email             text,
    invited_by        uuid,
    invited_at        timestamptz,
    disabled_at       timestamptz,
    last_seen_at      timestamptz,
    erase_started_at  timestamptz
);

-- organizations ---------------------------------------------------------------
create table if not exists public.organizations (
    id          uuid not null default gen_random_uuid(),
    slug        text not null,
    name        text not null,
    kind        text not null,
    country     text not null default 'IN',
    region      text,
    created_at  timestamptz not null default now()
);

-- rule_profiles ---------------------------------------------------------------
create table if not exists public.rule_profiles (
    id                uuid not null default gen_random_uuid(),
    code              text not null,
    name              text not null,
    bracket_default   text not null default 'double_elim',
    protest_fee_inr   integer default 500,
    warnings_per_foul integer default 2,
    fouls_to_lose     integer default 2,
    weight_classes    jsonb not null default '[]'::jsonb,
    created_at        timestamptz not null default now()
);

-- events ----------------------------------------------------------------------
create table if not exists public.events (
    id                          uuid not null default gen_random_uuid(),
    organization_id             uuid not null,
    rule_profile_id             uuid,
    slug                        text not null,
    name                        text not null,
    status                      text not null default 'draft',
    starts_at                   timestamptz not null,
    ends_at                     timestamptz,
    venue_name                  text,
    venue_city                  text,
    venue_state                 text,
    cover_url                   text,
    description                 text,
    entry_fee_inr               integer default 0,
    currency                    text not null default 'INR',
    prize_pool_inr              bigint default 0,
    registration_opens_at       timestamptz,
    registration_closes_at      timestamptz,
    weigh_in_starts_at          timestamptz,
    weigh_in_ends_at            timestamptz,
    hand                        text not null default 'right',
    created_by                  uuid,
    created_at                  timestamptz not null default now(),
    registration_published_at   timestamptz,
    registration_closed_at      timestamptz,
    payment_provider            text not null default 'manual_upi',
    upi_id                      text,
    upi_payee_name              text,
    entry_fee_default_inr       integer default 500,
    fee_overrides               jsonb default '{}'::jsonb,
    logo_url                    text,
    banner_url                  text,
    primary_color               text default '#0f3d2e',
    accent_color                text default '#f5c518',
    text_on_primary             text default '#ffffff',
    id_card_template            text default 'tnawa_v1',
    id_card_org_name            text,
    id_card_event_title         text,
    id_card_subtitle            text,
    id_card_footer              text,
    id_card_signatory_name      text,
    id_card_signatory_title     text,
    id_card_signature_url       text,
    poster_url                  text,
    poster_kind                 text,
    circular_url                text,
    payment_mode                text not null default 'online_upi',
    id_card_org_name_size       smallint,
    id_card_event_title_size    smallint,
    bracket_format              text not null default 'double_elim',
    entry_fee_offline_inr       integer,
    entry_fee_para_inr          integer,
    -- Per-event Challonge integration (migration 0045). When enabled,
    -- /admin/events/:id/categories pushes one Challonge tournament per
    -- category under the configured Premier subdomain. The api_key is
    -- write-only from the UI and never returned to the client.
    challonge_enabled           boolean not null default false,
    challonge_api_key           text,
    challonge_username          text,
    challonge_subdomain         text
);

-- athletes --------------------------------------------------------------------
create table if not exists public.athletes (
    id              uuid not null,
    date_of_birth   date,
    gender          text,
    state           text,
    district        text,
    pan_masked      text,
    aadhaar_masked  text,
    created_at      timestamptz not null default now(),
    is_para         boolean not null default false,
    para_class      text,
    para_posture    text,
    aadhaar         text
);

-- registrations ---------------------------------------------------------------
create table if not exists public.registrations (
    id                  uuid not null default gen_random_uuid(),
    event_id            uuid not null,
    athlete_id          uuid,
    weight_class_code   text,
    hand                text not null default 'right',
    status              text not null default 'pending',
    paid_amount_inr     integer default 0,
    payment_ref         text,
    created_at          timestamptz not null default now(),
    chest_no            integer,
    initial             text,
    full_name           text,
    dob                 date,
    division            text,
    affiliation_kind    text,
    district            text,
    team                text,
    mobile              text,
    aadhaar_masked      text,
    declared_weight_kg  numeric(5,2),
    age_categories      text[],
    youth_hand          text,
    senior_hand         text,
    photo_url           text,
    photo_bytes         integer,
    submitted_by        text default 'self',
    is_para             boolean not null default false,
    para_class          text,
    para_posture        text,
    gender              text,
    nonpara_classes     text[],
    nonpara_hand        text,
    para_codes          text[],
    para_hand           text,
    nonpara_hands       text[],
    public_token        text not null default encode(gen_random_bytes(8), 'hex'),
    aadhaar             text,
    checkin_status      text not null default 'not_arrived',
    channel             text not null default 'offline',
    lifecycle_status    text not null default 'active',
    discipline_status   text not null default 'clear',
    weight_overrides    jsonb not null default '[]'::jsonb
);

-- payments --------------------------------------------------------------------
create table if not exists public.payments (
    id              uuid not null default gen_random_uuid(),
    registration_id uuid not null,
    amount_inr      integer not null,
    method          text not null default 'manual_upi',
    utr             text,
    proof_url       text,
    status          text not null default 'pending',
    verified_by     uuid,
    verified_at     timestamptz,
    notes           text,
    created_at      timestamptz default now()
);

-- payment_collections ---------------------------------------------------------
create table if not exists public.payment_collections (
    id               uuid not null default gen_random_uuid(),
    payment_id       uuid not null,
    amount_inr       integer not null,
    method           text not null,
    reference        text,
    collected_by     uuid,
    collected_at     timestamptz not null default now(),
    reversed_at      timestamptz,
    reversed_by      uuid,
    reversal_reason  text,
    payer_label      text
);

-- payment_proofs --------------------------------------------------------------
create table if not exists public.payment_proofs (
    id          uuid not null default gen_random_uuid(),
    payment_id  uuid not null,
    utr         text not null,
    proof_url   text not null,
    created_at  timestamptz not null default now(),
    deleted_at  timestamptz
);

-- weigh_ins -------------------------------------------------------------------
create table if not exists public.weigh_ins (
    id              uuid not null default gen_random_uuid(),
    registration_id uuid not null,
    measured_kg     numeric(5,2) not null,
    live_photo_url  text,
    scale_photo_url text,
    weighed_by      uuid,
    weighed_at      timestamptz default now()
);

-- venue_tables ----------------------------------------------------------------
create table if not exists public.venue_tables (
    id        uuid not null default gen_random_uuid(),
    event_id  uuid not null,
    number    integer not null,
    label     text
);

-- categories ------------------------------------------------------------------
create table if not exists public.categories (
    id                 uuid not null default gen_random_uuid(),
    event_id           uuid not null,
    weight_class_code  text not null,
    hand               text not null default 'right',
    division           text not null,
    display_name       text not null,
    status             text not null default 'pending',
    bracket_format     text not null default 'double_elim',
    created_at         timestamptz not null default now(),
    table_no           smallint
);

-- hubs ------------------------------------------------------------------------
create table if not exists public.hubs (
    id            uuid not null default gen_random_uuid(),
    event_id      uuid not null,
    table_id      uuid,
    code          text not null,
    display_name  text not null,
    status        text not null default 'offline',
    public_key    bytea,
    last_seen_at  timestamptz,
    created_at    timestamptz not null default now()
);

-- hub_devices -----------------------------------------------------------------
create table if not exists public.hub_devices (
    id            uuid not null default gen_random_uuid(),
    hub_id        uuid not null,
    kind          text not null,
    label         text,
    public_key    bytea,
    last_seen_at  timestamptz,
    created_at    timestamptz not null default now()
);

-- category_assignments --------------------------------------------------------
create table if not exists public.category_assignments (
    id          uuid not null default gen_random_uuid(),
    category_id uuid not null,
    hub_id      uuid not null,
    started_at  timestamptz not null default now(),
    ended_at    timestamptz,
    reason      text
);

-- chest_blocks ----------------------------------------------------------------
create table if not exists public.chest_blocks (
    event_id    uuid not null,
    group_key   text not null,
    base        integer not null,
    created_at  timestamptz not null default now()
);

-- entries ---------------------------------------------------------------------
create table if not exists public.entries (
    id              uuid not null default gen_random_uuid(),
    registration_id uuid not null,
    division        text not null,
    age_band        text not null,
    weight_class    text not null,
    hand            text not null,
    category_code   text not null,
    seed            integer
);

-- fixtures --------------------------------------------------------------------
create table if not exists public.fixtures (
    id                       uuid not null default gen_random_uuid(),
    event_id                 uuid not null,
    category_code            text not null,
    round_no                 integer not null,
    match_no                 integer not null,
    entry_a_id               uuid,
    entry_b_id               uuid,
    next_match_id            uuid,
    bracket_side             text not null default 'W',
    next_round_no            integer,
    next_match_no            integer,
    next_bracket_side        text,
    loser_next_round_no      integer,
    loser_next_match_no      integer,
    loser_next_bracket_side  text,
    best_of                  smallint not null default 1,
    winner_entry_id          uuid,
    created_at               timestamptz not null default now(),
    status                   text not null default 'scheduled',
    score_a                  smallint not null default 0,
    score_b                  smallint not null default 0,
    method                   text,
    mat_no                   smallint,
    started_at               timestamptz,
    completed_at             timestamptz,
    updated_by               uuid,
    updated_at               timestamptz not null default now()
);

-- audit_log -------------------------------------------------------------------
create table if not exists public.audit_log (
    id            bigint not null default nextval('public.audit_log_id_seq'::regclass),
    event_id      uuid,
    actor_id      uuid,
    actor_label   text,
    action        text not null,
    target_table  text,
    target_id     text,
    payload       jsonb,
    client_ip     text,
    created_at    timestamptz default now()
);
alter sequence public.audit_log_id_seq owned by public.audit_log.id;

-- event_log -------------------------------------------------------------------
create table if not exists public.event_log (
    id          uuid not null,
    event_id    uuid,
    category_id uuid,
    hub_id      uuid,
    device_id   uuid,
    actor_id    uuid,
    topic       text not null,
    payload     jsonb not null,
    client_ts   timestamptz not null,
    server_ts   timestamptz not null default now(),
    prev_hash   bytea,
    hash        bytea not null,
    signature   bytea
);

-- =============================================================================
-- PRIMARY KEYS
-- =============================================================================
alter table public.profiles             add constraint profiles_pkey             primary key (id);
alter table public.organizations        add constraint organizations_pkey        primary key (id);
alter table public.rule_profiles        add constraint rule_profiles_pkey        primary key (id);
alter table public.events               add constraint events_pkey               primary key (id);
alter table public.athletes             add constraint athletes_pkey             primary key (id);
alter table public.registrations        add constraint registrations_pkey        primary key (id);
alter table public.payments             add constraint payments_pkey             primary key (id);
alter table public.payment_collections  add constraint payment_collections_pkey  primary key (id);
alter table public.payment_proofs       add constraint payment_proofs_pkey       primary key (id);
alter table public.weigh_ins            add constraint weigh_ins_pkey            primary key (id);
alter table public.venue_tables         add constraint venue_tables_pkey         primary key (id);
alter table public.categories           add constraint categories_pkey           primary key (id);
alter table public.hubs                 add constraint hubs_pkey                 primary key (id);
alter table public.hub_devices          add constraint hub_devices_pkey          primary key (id);
alter table public.category_assignments add constraint category_assignments_pkey primary key (id);
alter table public.chest_blocks         add constraint chest_blocks_pkey         primary key (event_id, base);
alter table public.entries              add constraint entries_pkey              primary key (id);
alter table public.fixtures             add constraint fixtures_pkey             primary key (id);
alter table public.audit_log            add constraint audit_log_pkey            primary key (id);
alter table public.event_log            add constraint event_log_pkey            primary key (id);

-- =============================================================================
-- UNIQUE CONSTRAINTS
-- =============================================================================
alter table public.organizations add constraint organizations_slug_key unique (slug);
alter table public.rule_profiles add constraint rule_profiles_code_key unique (code);
alter table public.events        add constraint events_slug_key        unique (slug);
alter table public.categories    add constraint categories_event_id_weight_class_code_hand_key unique (event_id, weight_class_code, hand);
alter table public.hubs          add constraint hubs_event_id_code_key unique (event_id, code);
alter table public.venue_tables  add constraint venue_tables_event_id_number_key unique (event_id, number);
alter table public.entries       add constraint entries_registration_id_division_age_band_weight_class_hand_key unique (registration_id, division, age_band, weight_class, hand);
alter table public.fixtures      add constraint fixtures_event_cat_side_round_match_key unique (event_id, category_code, bracket_side, round_no, match_no);
alter table public.registrations add constraint registrations_event_id_athlete_id_weight_class_code_hand_key unique (event_id, athlete_id, weight_class_code, hand);

-- =============================================================================
-- CHECK CONSTRAINTS
-- =============================================================================
alter table public.organizations add constraint organizations_kind_check check (kind = any (array['federation'::text, 'organiser'::text, 'league'::text, 'club'::text]));
alter table public.profiles      add constraint profiles_role_check      check (role = any (array['athlete'::text, 'operator'::text, 'super_admin'::text]));

alter table public.rule_profiles add constraint rule_profiles_bracket_default_check
    check (bracket_default = any (array['double_elim'::text, 'single_elim'::text, 'round_robin'::text, 'top8_no_loser'::text, 'six_round_supermatch'::text]));

alter table public.events add constraint events_bracket_format_check         check (bracket_format = any (array['double_elim'::text, 'single_elim'::text, 'round_robin'::text]));
alter table public.events add constraint events_entry_fee_offline_inr_check  check (entry_fee_offline_inr is null or entry_fee_offline_inr >= 0);
alter table public.events add constraint events_entry_fee_para_inr_check     check (entry_fee_para_inr    is null or entry_fee_para_inr    >= 0);
alter table public.events add constraint events_hand_check                   check (hand = any (array['right'::text, 'left'::text, 'both'::text]));
alter table public.events add constraint events_id_card_event_title_size_chk check (id_card_event_title_size is null or (id_card_event_title_size between 6 and 16));
alter table public.events add constraint events_id_card_org_name_size_chk    check (id_card_org_name_size    is null or (id_card_org_name_size    between 5 and 14));
alter table public.events add constraint events_payment_mode_check           check (payment_mode = any (array['online_upi'::text, 'offline'::text, 'hybrid'::text]));
alter table public.events add constraint events_payment_provider_check       check (payment_provider = any (array['manual_upi'::text, 'razorpay'::text, 'none'::text]));
alter table public.events add constraint events_poster_kind_check            check (poster_kind = any (array['image'::text, 'pdf'::text]));
alter table public.events add constraint events_status_check                 check (status = any (array['draft'::text, 'open'::text, 'live'::text, 'completed'::text, 'archived'::text]));

alter table public.athletes add constraint athletes_aadhaar_format     check (aadhaar is null or aadhaar ~ '^[0-9]{12}$');
alter table public.athletes add constraint athletes_gender_check       check (gender = any (array['M'::text, 'F'::text, 'O'::text]));
alter table public.athletes add constraint athletes_para_posture_check check (para_posture = any (array['Standing'::text, 'Seated'::text]));

alter table public.registrations add constraint registrations_aadhaar_format          check (aadhaar is null or aadhaar ~ '^[0-9]{12}$');
alter table public.registrations add constraint registrations_affiliation_kind_check  check (affiliation_kind = any (array['District'::text, 'Team'::text]));
alter table public.registrations add constraint registrations_channel_check           check (channel = any (array['online'::text, 'offline'::text]));
alter table public.registrations add constraint registrations_checkin_status_check    check (checkin_status = any (array['not_arrived'::text, 'weighed_in'::text, 'no_show'::text]));
alter table public.registrations add constraint registrations_discipline_status_check check (discipline_status = any (array['clear'::text, 'disqualified'::text]));
alter table public.registrations add constraint registrations_division_check          check (division = any (array['Men'::text, 'Women'::text, 'Para Men'::text, 'Para Women'::text]));
alter table public.registrations add constraint registrations_gender_check            check (gender = any (array['M'::text, 'F'::text, 'O'::text]));
alter table public.registrations add constraint registrations_lifecycle_status_check  check (lifecycle_status = any (array['active'::text, 'withdrawn'::text]));
alter table public.registrations add constraint registrations_nonpara_hand_check      check (nonpara_hand = any (array['R'::text, 'L'::text, 'B'::text]));
alter table public.registrations add constraint registrations_para_hand_check         check (para_hand = any (array['R'::text, 'L'::text, 'B'::text]));
alter table public.registrations add constraint registrations_para_posture_check      check (para_posture = any (array['Standing'::text, 'Seated'::text]));
alter table public.registrations add constraint registrations_senior_hand_check       check (senior_hand = any (array['R'::text, 'L'::text, 'B'::text]));
alter table public.registrations add constraint registrations_status_check            check (status = any (array['pending'::text, 'paid'::text, 'weighed_in'::text, 'withdrawn'::text, 'disqualified'::text]));
alter table public.registrations add constraint registrations_youth_hand_check        check (youth_hand = any (array['R'::text, 'L'::text, 'B'::text]));

alter table public.payments add constraint payments_method_check check (method = any (array['manual_upi'::text, 'razorpay'::text, 'cash'::text, 'waiver'::text]));
alter table public.payments add constraint payments_status_check check (status = any (array['pending'::text, 'submitted'::text, 'verified'::text, 'rejected'::text]));

alter table public.payment_collections add constraint payment_collections_amount_inr_check check (amount_inr >= 0);
alter table public.payment_collections add constraint payment_collections_method_check     check (method = any (array['manual_upi'::text, 'razorpay'::text, 'cash'::text, 'waiver'::text]));

alter table public.categories add constraint categories_hand_check     check (hand = any (array['right'::text, 'left'::text]));
alter table public.categories add constraint categories_status_check   check (status = any (array['pending'::text, 'calling'::text, 'live'::text, 'paused'::text, 'completed'::text]));
alter table public.categories add constraint categories_table_no_check check (table_no is null or table_no > 0);

alter table public.hubs        add constraint hubs_status_check      check (status = any (array['offline'::text, 'online'::text, 'degraded'::text, 'retired'::text]));
alter table public.hub_devices add constraint hub_devices_kind_check check (kind   = any (array['controller'::text, 'mc_tablet'::text, 'sideref_tablet'::text, 'checkin_tablet'::text, 'camera'::text, 'led_display'::text]));

alter table public.chest_blocks add constraint chest_blocks_base_check check (base >= 1000 and (base % 100) = 0);

alter table public.entries  add constraint entries_hand_check                       check (hand = any (array['R'::text, 'L'::text]));
alter table public.fixtures add constraint fixtures_best_of_check                   check (best_of = any (array[1, 3, 5]));
alter table public.fixtures add constraint fixtures_bracket_side_check              check (bracket_side = any (array['W'::text, 'L'::text, 'GF'::text]));
alter table public.fixtures add constraint fixtures_loser_next_bracket_side_check   check (loser_next_bracket_side is null or (loser_next_bracket_side = any (array['W'::text, 'L'::text, 'GF'::text])));
alter table public.fixtures add constraint fixtures_method_check                    check (method is null or (method = any (array['points'::text, 'pin'::text, 'disqualification'::text, 'walkover'::text, 'forfeit'::text, 'injury'::text])));
alter table public.fixtures add constraint fixtures_next_bracket_side_check         check (next_bracket_side is null or (next_bracket_side = any (array['W'::text, 'L'::text, 'GF'::text])));
alter table public.fixtures add constraint fixtures_status_check                    check (status = any (array['scheduled'::text, 'in_progress'::text, 'completed'::text, 'void'::text]));

-- =============================================================================
-- FOREIGN KEYS (after all tables exist; order is irrelevant)
-- =============================================================================
alter table public.profiles
    add constraint profiles_id_fkey         foreign key (id)         references auth.users(id) on delete cascade,
    add constraint profiles_invited_by_fkey foreign key (invited_by) references public.profiles(id);

alter table public.events
    add constraint events_created_by_fkey      foreign key (created_by)      references public.profiles(id)      on delete set null,
    add constraint events_organization_id_fkey foreign key (organization_id) references public.organizations(id) on delete cascade,
    add constraint events_rule_profile_id_fkey foreign key (rule_profile_id) references public.rule_profiles(id);

alter table public.athletes
    add constraint athletes_id_fkey foreign key (id) references public.profiles(id) on delete cascade;

alter table public.registrations
    add constraint registrations_athlete_id_fkey foreign key (athlete_id) references public.athletes(id) on delete set null,
    add constraint registrations_event_id_fkey   foreign key (event_id)   references public.events(id)   on delete cascade;

alter table public.payments
    add constraint payments_registration_id_fkey foreign key (registration_id) references public.registrations(id) on delete cascade,
    add constraint payments_verified_by_fkey     foreign key (verified_by)     references public.profiles(id)      on delete set null;

alter table public.payment_collections
    add constraint payment_collections_collected_by_fkey foreign key (collected_by) references public.profiles(id) on delete set null,
    add constraint payment_collections_payment_id_fkey   foreign key (payment_id)   references public.payments(id) on delete cascade,
    add constraint payment_collections_reversed_by_fkey  foreign key (reversed_by)  references public.profiles(id) on delete set null;

alter table public.payment_proofs
    add constraint payment_proofs_payment_id_fkey foreign key (payment_id) references public.payments(id) on delete cascade;

alter table public.weigh_ins
    add constraint weigh_ins_registration_id_fkey foreign key (registration_id) references public.registrations(id) on delete cascade,
    add constraint weigh_ins_weighed_by_fkey      foreign key (weighed_by)      references public.profiles(id)      on delete set null;

alter table public.venue_tables
    add constraint venue_tables_event_id_fkey foreign key (event_id) references public.events(id) on delete cascade;

alter table public.categories
    add constraint categories_event_id_fkey foreign key (event_id) references public.events(id) on delete cascade;

alter table public.hubs
    add constraint hubs_event_id_fkey foreign key (event_id) references public.events(id)        on delete cascade,
    add constraint hubs_table_id_fkey foreign key (table_id) references public.venue_tables(id) on delete set null;

alter table public.hub_devices
    add constraint hub_devices_hub_id_fkey foreign key (hub_id) references public.hubs(id) on delete cascade;

alter table public.category_assignments
    add constraint category_assignments_category_id_fkey foreign key (category_id) references public.categories(id) on delete cascade,
    add constraint category_assignments_hub_id_fkey      foreign key (hub_id)      references public.hubs(id)       on delete cascade;

alter table public.chest_blocks
    add constraint chest_blocks_event_id_fkey foreign key (event_id) references public.events(id) on delete cascade;

alter table public.entries
    add constraint entries_registration_id_fkey foreign key (registration_id) references public.registrations(id) on delete cascade;

alter table public.fixtures
    add constraint fixtures_entry_a_id_fkey      foreign key (entry_a_id)      references public.entries(id)  on delete set null,
    add constraint fixtures_entry_b_id_fkey      foreign key (entry_b_id)      references public.entries(id)  on delete set null,
    add constraint fixtures_event_id_fkey        foreign key (event_id)        references public.events(id)   on delete cascade,
    add constraint fixtures_next_match_id_fkey   foreign key (next_match_id)   references public.fixtures(id) on delete set null,
    add constraint fixtures_updated_by_fkey      foreign key (updated_by)      references public.profiles(id) on delete set null,
    add constraint fixtures_winner_entry_id_fkey foreign key (winner_entry_id) references public.entries(id)  on delete set null;

alter table public.audit_log
    add constraint audit_log_actor_id_fkey foreign key (actor_id) references public.profiles(id),
    add constraint audit_log_event_id_fkey foreign key (event_id) references public.events(id) on delete set null;

alter table public.event_log
    add constraint event_log_actor_id_fkey    foreign key (actor_id)    references public.profiles(id)    on delete set null,
    add constraint event_log_category_id_fkey foreign key (category_id) references public.categories(id) on delete cascade,
    add constraint event_log_device_id_fkey   foreign key (device_id)   references public.hub_devices(id) on delete set null,
    add constraint event_log_event_id_fkey    foreign key (event_id)    references public.events(id)     on delete cascade,
    add constraint event_log_hub_id_fkey      foreign key (hub_id)      references public.hubs(id)       on delete set null;

-- =============================================================================
-- INDEXES (non-constraint-backed)
-- =============================================================================
create index if not exists audit_log_action_idx on public.audit_log (action,   created_at desc);
create index if not exists audit_log_actor_idx  on public.audit_log (actor_id, created_at desc);
create index if not exists audit_log_event_idx  on public.audit_log (event_id, created_at desc);

create index if not exists categories_event_idx       on public.categories (event_id);
create index if not exists categories_event_table_idx on public.categories (event_id, table_no);

create unique index if not exists category_assignments_active_idx
    on public.category_assignments (category_id) where ended_at is null;

create index if not exists chest_blocks_event_group_idx on public.chest_blocks (event_id, group_key, base);

create index if not exists entries_category_idx on public.entries (category_code);

create index if not exists event_log_category_idx on public.event_log (category_id, server_ts);
create index if not exists event_log_event_idx    on public.event_log (event_id,    server_ts);
create index if not exists event_log_hub_idx      on public.event_log (hub_id,      client_ts);
create index if not exists event_log_topic_idx    on public.event_log (topic);

create index if not exists events_starts_at_idx on public.events (starts_at);
create index if not exists events_status_idx    on public.events (status);

create index if not exists fixtures_event_idx        on public.fixtures (event_id, category_code);
create index if not exists fixtures_event_status_idx on public.fixtures (event_id, status, mat_no, round_no, match_no);

create index if not exists payment_collections_active_idx
    on public.payment_collections (payment_id) where reversed_at is null;
create index if not exists payment_collections_payer_label_idx
    on public.payment_collections (payer_label) where payer_label is not null;
create index if not exists payment_collections_payment_idx
    on public.payment_collections (payment_id, collected_at desc);

create index if not exists payment_proofs_payment_idx on public.payment_proofs (payment_id, created_at desc);

create index if not exists payments_registration_id_idx on public.payments (registration_id);
create index if not exists payments_registration_idx    on public.payments (registration_id);
create index if not exists payments_status_idx          on public.payments (status);

create index if not exists profiles_erase_started_idx on public.profiles (erase_started_at) where erase_started_at is not null;

create unique index if not exists registrations_event_athlete_uidx on public.registrations (event_id, athlete_id);
create index        if not exists registrations_event_checkin_idx  on public.registrations (event_id, checkin_status);
create unique index if not exists registrations_event_chest_no_idx on public.registrations (event_id, chest_no);
create index        if not exists registrations_event_discipline_idx on public.registrations (event_id, discipline_status) where discipline_status = 'disqualified'::text;
create index        if not exists registrations_event_district_idx  on public.registrations (event_id, district);
create index        if not exists registrations_event_lifecycle_idx on public.registrations (event_id, lifecycle_status);
create index        if not exists registrations_event_status_idx    on public.registrations (event_id, status);
create index        if not exists registrations_event_submitted_created_idx on public.registrations (event_id, submitted_by, created_at desc);
create unique index if not exists registrations_public_token_idx    on public.registrations (public_token);

create index if not exists weigh_ins_registration_idx on public.weigh_ins (registration_id, weighed_at desc);

-- =============================================================================
-- FUNCTIONS
-- =============================================================================

create or replace function public.role_at_least(min_role text)
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (
    select 1
    from profiles p
    where p.id = auth.uid()
      and p.disabled_at is null
      and case min_role
        when 'operator'    then p.role in ('operator','super_admin')
        when 'super_admin' then p.role = 'super_admin'
        else false
      end
  );
$$;

create or replace function public.chest_group_key(p_district text, p_team text)
returns text language sql immutable
as $$
  select coalesce(
    nullif(btrim(p_district), ''),
    case when nullif(btrim(p_team), '') is not null then 'team:' || btrim(p_team) else null end,
    '__unassigned__'
  );
$$;

create or replace function public.next_chest_no(p_event uuid)
returns integer language plpgsql
as $$
declare n int;
begin
  select coalesce(max(chest_no), 1000) + 1 into n
    from registrations where event_id = p_event;
  return n;
end$$;

create or replace function public.assign_chest_no()
returns trigger language plpgsql
as $$
declare
  v_key      text;
  v_base     int;
  v_max      int;
  v_assigned boolean := false;
begin
  if NEW.chest_no is not null or NEW.event_id is null then
    return NEW;
  end if;

  v_key := chest_group_key(NEW.district, NEW.team);
  perform pg_advisory_xact_lock(hashtext('chest_no:' || NEW.event_id::text));

  for v_base in
    select base from chest_blocks
     where event_id = NEW.event_id and group_key = v_key
     order by base
  loop
    select coalesce(max(chest_no), v_base - 1)
      into v_max
      from registrations
     where event_id = NEW.event_id
       and chest_no between v_base and v_base + 99;
    if v_max < v_base + 99 then
      NEW.chest_no := v_max + 1;
      v_assigned := true;
      exit;
    end if;
  end loop;

  if not v_assigned then
    select coalesce(max(base), 900) + 100
      into v_base
      from chest_blocks
     where event_id = NEW.event_id;
    if v_base < 1000 then v_base := 1000; end if;
    insert into chest_blocks(event_id, group_key, base)
      values (NEW.event_id, v_key, v_base);
    NEW.chest_no := v_base + 1;
  end if;

  return NEW;
end
$$;

create or replace function public.event_log_immutable()
returns trigger language plpgsql
as $$
begin
  raise exception 'event_log is append-only (op=%)', tg_op;
end$$;

create or replace function public.registrations_mark_weighed_in()
returns trigger language plpgsql
as $$
begin
  update registrations
     set checkin_status = 'weighed_in'
   where id = new.registration_id
     and checkin_status <> 'weighed_in';
  return new;
end;
$$;

create or replace function public.fill_next_slot(
  p_next_id uuid, p_source_match integer, p_entry_id uuid,
  p_actor uuid, p_now timestamptz
) returns void
language plpgsql security definer set search_path = public
as $$
declare
  v_next         fixtures%rowtype;
  v_target_side  char;
  v_existing     uuid;
  v_other        uuid;
  v_feeder_count int;
  v_after        fixtures%rowtype;
begin
  select * into v_next from fixtures where id = p_next_id for update;
  if not found then return; end if;

  if v_next.status in ('in_progress','completed') then
    raise exception 'downstream fixture % already %', v_next.id, v_next.status
      using errcode = 'P0002';
  end if;

  v_target_side := case when (p_source_match % 2) = 1 then 'A' else 'B' end;
  if v_target_side = 'A' then
    v_existing := v_next.entry_a_id;
    v_other    := v_next.entry_b_id;
  else
    v_existing := v_next.entry_b_id;
    v_other    := v_next.entry_a_id;
  end if;

  if v_existing is not null and v_existing <> p_entry_id and v_other is null then
    if v_target_side = 'A' then v_target_side := 'B'; else v_target_side := 'A'; end if;
    v_existing := v_other;
    v_other    := case when v_target_side = 'A' then v_next.entry_b_id else v_next.entry_a_id end;
  end if;

  if v_existing is not null and v_existing <> p_entry_id then
    raise exception 'downstream fixture % side % already filled with different entry',
      v_next.id, v_target_side using errcode = 'P0001';
  end if;

  if v_target_side = 'A' then
    update fixtures set entry_a_id = p_entry_id, updated_by = p_actor, updated_at = p_now where id = p_next_id;
  else
    update fixtures set entry_b_id = p_entry_id, updated_by = p_actor, updated_at = p_now where id = p_next_id;
  end if;

  if v_other is null then
    select count(*) into v_feeder_count
      from fixtures src
     where src.event_id      = v_next.event_id
       and src.category_code = v_next.category_code
       and src.status        not in ('completed','void')
       and src.id            <> p_next_id
       and (
         (src.next_round_no = v_next.round_no
          and src.next_match_no = v_next.match_no
          and coalesce(src.next_bracket_side, src.bracket_side) = v_next.bracket_side)
         or
         (src.loser_next_round_no = v_next.round_no
          and src.loser_next_match_no = v_next.match_no
          and coalesce(src.loser_next_bracket_side, 'L') = v_next.bracket_side)
       );

    if v_feeder_count = 0 then
      update fixtures
         set status          = 'completed',
             winner_entry_id = p_entry_id,
             method          = 'walkover',
             completed_at    = p_now,
             started_at      = coalesce(started_at, p_now),
             updated_by      = p_actor,
             updated_at      = p_now
       where id = p_next_id
       returning * into v_after;

      if v_after.next_round_no is not null then
        perform fill_next_slot(
          (select id from fixtures
            where event_id      = v_after.event_id
              and category_code = v_after.category_code
              and bracket_side  = coalesce(v_after.next_bracket_side, v_after.bracket_side)
              and round_no      = v_after.next_round_no
              and match_no      = v_after.next_match_no
            limit 1),
          v_after.match_no, p_entry_id, p_actor, p_now);
      end if;
    end if;
  end if;
end;
$$;

create or replace function public.apply_fixture_complete(
  p_fixture_id uuid, p_winner character, p_score_a integer, p_score_b integer,
  p_method text, p_actor uuid
) returns table (
  out_id uuid, out_bracket_side text, out_round_no integer, out_match_no integer,
  out_status text, out_winner_entry_id uuid
)
language plpgsql security definer set search_path = public
as $$
declare
  v_fx              fixtures%rowtype;
  v_winner_entry_id uuid;
  v_loser_entry_id  uuid;
  v_next_id         uuid;
  v_loser_next_id   uuid;
  v_now             timestamptz := now();
begin
  if p_winner not in ('A','B') then
    raise exception 'invalid winner %', p_winner using errcode = '22023';
  end if;

  select * into v_fx from fixtures where id = p_fixture_id for update;
  if not found then
    raise exception 'fixture % not found', p_fixture_id using errcode = 'P0003';
  end if;

  if v_fx.status = 'completed' and v_fx.winner_entry_id is not null then
    if (p_winner = 'A' and v_fx.winner_entry_id = v_fx.entry_a_id)
       or (p_winner = 'B' and v_fx.winner_entry_id = v_fx.entry_b_id) then
      return query
        select v_fx.id, v_fx.bracket_side, v_fx.round_no, v_fx.match_no,
               v_fx.status, v_fx.winner_entry_id;
      return;
    else
      raise exception 'fixture % already completed with different winner', p_fixture_id
        using errcode = 'P0001';
    end if;
  end if;

  if p_winner = 'A' then
    v_winner_entry_id := v_fx.entry_a_id;
    v_loser_entry_id  := v_fx.entry_b_id;
  else
    v_winner_entry_id := v_fx.entry_b_id;
    v_loser_entry_id  := v_fx.entry_a_id;
  end if;

  if v_winner_entry_id is null then
    raise exception 'fixture % side % has no entry', p_fixture_id, p_winner
      using errcode = '22023';
  end if;

  update fixtures
     set status          = 'completed',
         winner_entry_id = v_winner_entry_id,
         score_a         = coalesce(p_score_a, score_a),
         score_b         = coalesce(p_score_b, score_b),
         method          = coalesce(p_method, method),
         completed_at    = coalesce(completed_at, v_now),
         started_at      = coalesce(started_at, v_now),
         updated_by      = p_actor,
         updated_at      = v_now
   where id = p_fixture_id;

  if v_fx.next_round_no is not null and v_fx.next_match_no is not null then
    select fixtures.id into v_next_id
      from fixtures
     where fixtures.event_id      = v_fx.event_id
       and fixtures.category_code = v_fx.category_code
       and fixtures.bracket_side  = coalesce(v_fx.next_bracket_side, v_fx.bracket_side)
       and fixtures.round_no      = v_fx.next_round_no
       and fixtures.match_no      = v_fx.next_match_no
     for update;

    if v_next_id is not null then
      perform fill_next_slot(v_next_id, v_fx.match_no, v_winner_entry_id, p_actor, v_now);
    end if;
  end if;

  if v_loser_entry_id is not null
     and v_fx.loser_next_round_no is not null
     and v_fx.loser_next_match_no is not null then
    select fixtures.id into v_loser_next_id
      from fixtures
     where fixtures.event_id      = v_fx.event_id
       and fixtures.category_code = v_fx.category_code
       and fixtures.bracket_side  = coalesce(v_fx.loser_next_bracket_side, 'L')
       and fixtures.round_no      = v_fx.loser_next_round_no
       and fixtures.match_no      = v_fx.loser_next_match_no
     for update;

    if v_loser_next_id is not null then
      perform fill_next_slot(v_loser_next_id, v_fx.match_no, v_loser_entry_id, p_actor, v_now);
    end if;
  end if;

  return query
    select f.id, f.bracket_side, f.round_no, f.match_no,
           f.status, f.winner_entry_id
      from fixtures f
     where f.id in (
       select p_fixture_id
       union all select v_next_id where v_next_id is not null
       union all select v_loser_next_id where v_loser_next_id is not null
     );
end;
$$;

-- =============================================================================
-- VIEWS  (must come after their underlying tables AND helper functions)
-- =============================================================================

create or replace view public.payment_summary as
  select p.id as payment_id,
         p.registration_id,
         r.event_id,
         p.amount_inr as total_inr,
         p.status     as raw_status,
         coalesce(c.collected_inr, 0) as collected_inr,
         coalesce(c.received_inr,  0) as received_inr,
         coalesce(c.waived_inr,    0) as waived_inr,
         greatest(0, p.amount_inr - coalesce(c.collected_inr, 0)) as remaining_inr,
         case
           when p.status = 'rejected' then 'rejected'
           when p.amount_inr > 0 and coalesce(c.collected_inr, 0) >= p.amount_inr then 'verified'
           else 'pending'
         end as derived_status,
         c.latest_payer_label
    from payments p
    join registrations r on r.id = p.registration_id
    left join lateral (
      select coalesce(sum(pc.amount_inr) filter (where pc.reversed_at is null), 0)::int as collected_inr,
             coalesce(sum(pc.amount_inr) filter (where pc.reversed_at is null and pc.method <> 'waiver'), 0)::int as received_inr,
             coalesce(sum(pc.amount_inr) filter (where pc.reversed_at is null and pc.method  = 'waiver'), 0)::int as waived_inr,
             (select pc2.payer_label
                from payment_collections pc2
               where pc2.payment_id = p.id and pc2.reversed_at is null and pc2.payer_label is not null
               order by pc2.collected_at desc
               limit 1) as latest_payer_label
        from payment_collections pc
       where pc.payment_id = p.id
    ) c on true;

create or replace view public.event_payment_totals as
  select event_id,
         coalesce(sum(collected_inr), 0)::int as collected_inr,
         coalesce(sum(received_inr),  0)::int as received_inr,
         coalesce(sum(waived_inr),    0)::int as waived_inr,
         coalesce(sum(remaining_inr) filter (where derived_status = 'pending'), 0)::int as pending_inr,
         coalesce(sum(total_inr)     filter (where raw_status     = 'rejected'), 0)::int as rejected_inr,
         coalesce(sum(total_inr)     filter (where raw_status    <> 'rejected'), 0)::int as billable_inr,
         (coalesce(sum(total_inr)    filter (where raw_status    <> 'rejected'), 0)::int
          - coalesce(sum(waived_inr), 0)::int) as effective_inr,
         count(*) filter (where derived_status = 'verified')::int as collected_n,
         count(*) filter (where derived_status = 'pending')::int  as pending_n,
         count(*) filter (where waived_inr > 0)::int              as waived_n
    from payment_summary
   group by event_id;

create or replace view public.event_district_payment_totals as
  select r.event_id,
         coalesce(r.district, '—') as district,
         count(*)::int as athletes_n,
         coalesce(sum(s.collected_inr), 0)::int as collected_inr,
         coalesce(sum(s.received_inr),  0)::int as received_inr,
         coalesce(sum(s.waived_inr),    0)::int as waived_inr,
         coalesce(sum(s.remaining_inr) filter (where s.derived_status = 'pending'), 0)::int as pending_inr,
         count(*) filter (where s.derived_status = 'verified')::int as collected_n,
         count(*) filter (where s.derived_status = 'pending')::int  as pending_n,
         count(*) filter (where s.waived_inr > 0)::int              as waived_n
    from registrations r
    left join lateral (
      select * from payment_summary
       where registration_id = r.id
       order by payment_id desc
       limit 1
    ) s on true
   group by r.event_id, coalesce(r.district, '—');

create or replace function public.event_dashboard(p_id_or_slug text)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare
  v_event events%rowtype;
  v_counts jsonb;
  v_totals jsonb;
  v_districts jsonb;
begin
  if p_id_or_slug ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
    select * into v_event from events where id = p_id_or_slug::uuid;
  else
    select * into v_event from events where slug = p_id_or_slug;
  end if;
  if not found then return null; end if;

  select jsonb_build_object(
    'total_regs',    (select count(*) from registrations where event_id = v_event.id),
    'pending_pays',  (select count(*) from payment_summary
                       where event_id = v_event.id and derived_status = 'pending'),
    'verified_pays', (select count(*) from payment_summary
                       where event_id = v_event.id and derived_status = 'verified')
  ) into v_counts;

  select jsonb_build_object(
    'collected_inr', coalesce(sum(collected_inr), 0),
    'received_inr',  coalesce(sum(received_inr), 0),
    'waived_inr',    coalesce(sum(waived_inr), 0),
    'pending_inr',   coalesce(sum(remaining_inr) filter (where derived_status = 'pending'), 0),
    'billable_inr',  coalesce(sum(total_inr) filter (where raw_status <> 'rejected'), 0),
    'effective_inr', coalesce(sum(total_inr) filter (where raw_status <> 'rejected'), 0)
                       - coalesce(sum(waived_inr), 0),
    'collected_n',   count(*) filter (where derived_status = 'verified'),
    'pending_n',     count(*) filter (where derived_status = 'pending'),
    'waived_n',      count(*) filter (where waived_inr > 0)
  ) into v_totals
  from payment_summary
  where event_id = v_event.id;

  select coalesce(jsonb_agg(d order by d->>'athletes_n' desc), '[]'::jsonb) into v_districts
  from (
    select jsonb_build_object(
      'district',      coalesce(r.district, '—'),
      'athletes_n',    count(*),
      'collected_inr', coalesce(sum(s.collected_inr), 0),
      'received_inr',  coalesce(sum(s.received_inr), 0),
      'waived_inr',    coalesce(sum(s.waived_inr), 0),
      'pending_inr',   coalesce(sum(s.remaining_inr) filter (where s.derived_status = 'pending'), 0),
      'collected_n',   count(*) filter (where s.derived_status = 'verified'),
      'pending_n',     count(*) filter (where s.derived_status = 'pending'),
      'waived_n',      count(*) filter (where s.waived_inr > 0)
    ) as d
    from registrations r
    left join lateral (
      select * from payment_summary
       where registration_id = r.id
       order by payment_id desc
       limit 1
    ) s on true
    where r.event_id = v_event.id
    group by coalesce(r.district, '—')
  ) sub;

  return jsonb_build_object(
    'event',     to_jsonb(v_event),
    'counts',    v_counts,
    'totals',    v_totals,
    'districts', v_districts
  );
end;
$$;

create or replace function public.event_dashboard_counts(p_event_id uuid)
returns table (total_regs bigint, pending_pays bigint, verified_pays bigint)
language sql stable security definer set search_path = public
as $$
  with r as (select id from registrations where event_id = p_event_id)
  select
    (select count(*) from r),
    (select count(*) from payments p where p.registration_id in (select id from r) and p.status = 'pending'),
    (select count(*) from payments p where p.registration_id in (select id from r) and p.status = 'verified');
$$;

-- =============================================================================
-- ROW LEVEL SECURITY — enable + policies
-- =============================================================================
alter table public.athletes             enable row level security;
alter table public.audit_log            enable row level security;
alter table public.categories           enable row level security;
alter table public.category_assignments enable row level security;
alter table public.chest_blocks         enable row level security;
alter table public.entries              enable row level security;
alter table public.event_log            enable row level security;
alter table public.events               enable row level security;
alter table public.fixtures             enable row level security;
alter table public.hub_devices          enable row level security;
alter table public.hubs                 enable row level security;
alter table public.organizations        enable row level security;
alter table public.payment_collections  enable row level security;
alter table public.payment_proofs       enable row level security;
alter table public.payments             enable row level security;
alter table public.profiles             enable row level security;
alter table public.registrations        enable row level security;
alter table public.rule_profiles        enable row level security;
alter table public.venue_tables         enable row level security;
alter table public.weigh_ins            enable row level security;

create policy athletes_self        on public.athletes for select using (auth.uid() = id);
create policy athletes_self_update on public.athletes for update using (auth.uid() = id);

create policy audit_log_insert_any on public.audit_log for insert with check (auth.uid() is not null);
create policy audit_log_super_read on public.audit_log for select using (role_at_least('super_admin'));

create policy categories_public_read on public.categories
  for select using (exists (select 1 from events e where e.id = categories.event_id and e.status <> 'draft'));

create policy category_assignments_public_read on public.category_assignments for select using (true);

create policy entries_operator_all on public.entries
  for all using (role_at_least('operator')) with check (role_at_least('operator'));

create policy events_public_read on public.events
  for select using ((registration_published_at is not null) or role_at_least('operator'));
create policy events_super_admin_all on public.events
  for all using (role_at_least('super_admin')) with check (role_at_least('super_admin'));

create policy fixtures_operator_all on public.fixtures
  for all using (role_at_least('operator')) with check (role_at_least('operator'));

create policy hubs_public_read on public.hubs
  for select using (exists (select 1 from events e where e.id = hubs.event_id and e.status <> 'draft'));

create policy orgs_public_read on public.organizations for select using (true);

create policy payments_operator_read  on public.payments for select using (role_at_least('operator'));
create policy payments_operator_write on public.payments
  for all using (role_at_least('operator')) with check (role_at_least('operator'));
create policy payments_public_insert  on public.payments for insert with check (true);
create policy payments_self_read      on public.payments for select using (
  exists (select 1 from registrations r where r.id = payments.registration_id and r.athlete_id = auth.uid())
);

create policy profiles_self        on public.profiles for select using (auth.uid() = id);
create policy profiles_self_update on public.profiles for update using (auth.uid() = id);
create policy profiles_super_read  on public.profiles for select using (role_at_least('super_admin'));
create policy profiles_super_write on public.profiles for update
  using (role_at_least('super_admin')) with check (role_at_least('super_admin'));

create policy registrations_operator_all on public.registrations
  for all using (role_at_least('operator')) with check (role_at_least('operator'));
create policy registrations_self        on public.registrations for select using (auth.uid() = athlete_id);
create policy registrations_self_insert on public.registrations for insert with check (
  (auth.uid() = athlete_id) and exists (
    select 1 from events e
    where e.id = registrations.event_id
      and e.registration_published_at is not null
      and (e.registration_closed_at is null or e.registration_closed_at > now())
  )
);

create policy venue_tables_public_read on public.venue_tables
  for select using (exists (select 1 from events e where e.id = venue_tables.event_id and e.status <> 'draft'));

create policy weigh_ins_operator_insert on public.weigh_ins for insert with check (role_at_least('operator'));
create policy weigh_ins_operator_read   on public.weigh_ins for select using (role_at_least('operator'));

-- =============================================================================
-- GRANTS — Supabase managed roles baseline
-- =============================================================================
grant usage on schema public to anon, authenticated, service_role;
grant all    on all tables    in schema public to service_role;
grant all    on all sequences in schema public to service_role;
grant all    on all functions in schema public to service_role;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all tables in schema public to anon;

alter default privileges in schema public grant all on tables    to service_role;
alter default privileges in schema public grant all on sequences to service_role;
alter default privileges in schema public grant all on functions to service_role;
alter default privileges in schema public grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public grant select on tables to anon;

-- Tell PostgREST to reload its schema cache
notify pgrst, 'reload schema';
